# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170505_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_BL',
            field=models.CharField(default=datetime.datetime(2017, 5, 5, 16, 7, 13, 949762, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
